export const ADD_TIMELINE = 'ADD_TIMELINE'
export const ADD_TIMELINE_SUCCESS = 'ADD_TIMELINES_SUCCESS'
export const ADD_TIMELINE_FAILURE = 'ADD_TIMELINES_FAILURE'

export const DELETE_TIMELINE = 'DELETE_TIMELINE'
export const DELETE_TIMELINE_SUCCESS = 'DELETE_TIMELINE_SUCCESS'
export const DELETE_TIMELINE_FAILURE = 'DELETE_TIMELINE_FAILURE'

export const LOAD_TIMELINES = 'LOAD_TIMELINE'
export const LOAD_TIMELINES_SUCCESS = 'LOAD_TIMELINES_SUCCESS'
export const LOAD_TIMELINES_FAILURE = 'LOAD_TIMELINES_FAILURE'

export const EDIT_TIMELINE = 'EDIT_TIMELINE'
export const EDIT_TIMELINE_SUCCESS = 'EDIT_TIMELINE_SUCCESS'
export const EDIT_TIMELINE_FAILURE = 'EDIT_TIMELINE_FAILURE'