export const ADD_TIMELINE = 'ADD_TIMELINE'
export const ADD_TIMELINE_SUCCESS = 'ADD_TIMELINES_SUCCESS'
export const ADD_TIMELINE_FAILURE = 'ADD_TIMELINES_FAILURE'

export const DELETE_TIMELINE = 'DELETE_TIMELINE'
export const DELETE_TIMELINE_SUCCESS = 'DELETE_TIMELINE_SUCCESS'
export const DELETE_TIMELINE_FAILURE = 'DELETE_TIMELINE_FAILURE'

export const LOAD_TIMELINES = 'LOAD_TIMELINE'
export const LOAD_TIMELINES_SUCCESS = 'LOAD_TIMELINES_SUCCESS'
export const LOAD_TIMELINES_FAILURE = 'LOAD_TIMELINES_FAILURE'

export const EDIT_TIMELINE = 'EDIT_TIMELINE'
export const EDIT_TIMELINE_SUCCESS = 'EDIT_TIMELINE_SUCCESS'
export const EDIT_TIMELINE_FAILURE = 'EDIT_TIMELINE_FAILURE'



export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE'

export const LOAD_COMMENTS = 'LOAD_COMMENTS'
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'
export const LOAD_COMMENTS_FAILURE = 'LOAD_COMMENTS_FAILURE'

export const EDIT_COMMENT = 'EDIT_COMMENT'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE'


export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'