export const LOAD_POST = 'LOAD_POST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

export const ADD_POST = 'ADD_POST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE'

export const EDIT_POST = 'EDIT_POST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const LOGIN_PROCESS = 'LOGIN_PROCESS'
export const LOGIN_PROCESS_SUCCESS = 'LOGIN_PROCESS_SUCCESS'
export const LOGIN_PROCESS_FAILURE = 'LOGIN_PROCESS_FAILURE'

export const REGISTER_PROCESS = 'REGISTER_PROCESS'
export const REGISTER_PROCESS_SUCCESS = 'REGISTER_PROCESS_SUCCESS'
export const REGISTER_PROCESS_FAILURE = 'REGISTER_PROCESS_FAILURE'
