export const ADD_TIMELINE = 'ADD_TIMELINE'
export const ADD_TIMELINES_SUCCESS = 'ADD_TIMELINES_SUCCESS'
export const ADD_TIMELINES_FAILURE = 'ADD_TIMELINES_FAILURE'

export const EDIT_TIMELINE = 'EDIT_TIMELINE'
export const EDIT_TIMELINES_SUCCESS = 'EDIT_TIMELINES_SUCCESS'
export const EDIT_TIMELINES_FAILURE = 'EDIT_TIMELINES_FAILURE'

export const DELETE_TIMELINE = 'DELETE_TIMELINE'
export const DELETE_TIMELINES_SUCCESS = 'DELETE_TIMELINES_SUCCESS'
export const DELETE_TIMELINES_FAILURE = 'DELETE_TIMELINES_FAILURE'

export const LOAD_TIMELINE = 'LOAD_TIMELINE'
export const LOAD_TIMELINES_SUCCESS = 'LOAD_TIMELINES_SUCCESS'
export const LOAD_TIMELINES_FAILURE = 'LOAD_TIMELINES_FAILURE'
